
import Head from 'next/head'
import Header from '../components/header/index'
import Application from '../assets/forms/Issue.pdf'

export default function About() {
  return (
    <div>
      <Head>
        <title>Application for Enrolment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header height="h-96"/>
      <div className='w-full py-10'>
        <div className='w-10/12 bg-gray-100 m-auto'>
        <a href="https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" target="_blank" rel="noopener noreferrer" ><button>Download CV</button></a>
        </div>
      </div>
    </div>
  )
}
