
import Head from 'next/head'
import Header from '../components/header/index'

const Dates = [
  '8.40a.m. - Welcome and free play ',
'8 40a.m. - 9.10a.m. - Morning Ring ( Greeting, News, Weather and Topic Discussion)', 
'9 10a m - 10 15a.m. - Creative Activities', 
'10 15a.m. - 10.30a.m.- Free Play ',
'10.30a.m - 10.50a.m. - Music or Movement or Science/Mathematics Ring', 
'10.50a.m.- 11.15a.m.- Toilet Routine followed by Snack Time' ,
'11 15a.m. - 11.30a.m - Free Play', 
'11 30a.m. - 11 40a.m - Pack Away time', 
'11 40a m - 12 - Small Group Work ( worksheets. card or board games, puzzles ',
'12noon - 12 50pm - Story time followed by Home or Aftercare time'
];

export default function About() {
  return (
    <div>
      <Head>
        <title>Daily Program</title>
        <meta name="descriptions" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header height="h-96" image="https://images.unsplash.com/photo-1545558014-8692077e9b5c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80"/>
      <div className='w-full py-10 bg-gray-50'>
        <div className='flex w-10/12 m-auto'>
          <div className='w-1/2'>
            <h1 className='text-4xl font-bold mt-10 pb-8'>THE SCHOOL YEAR </h1>
            <p className='text-lg'>Our school follows the calendar set by the Western Cape Education Department for primary and secondary schools.</p>
            <h1 className='text-4xl font-bold py-8'>OUR DAILY PROGRAMME</h1>
            <ul>
              {Dates.map(d => <li className='py-2 text-md'>{d}</li>)}
            </ul>
          </div>
          <div className=' mt-10 ml-16 w-[30vw] h-[60vh]' style={{backgroundImage: 'url(https://scontent-cpt1-1.xx.fbcdn.net/v/t39.30808-6/274173214_349194807214417_3483669650949638549_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=730e14&_nc_ohc=llF3lJ52bGYAX8qPRVW&_nc_ht=scontent-cpt1-1.xx&oh=00_AfDp0YN7JzpXOiT2srvuA239_TJQ32g2fVx8cVUAtFTdiw&oe=6393A5CC)',backgroundSize: 'cover'}}>

          </div>
        </div>
      </div>
    </div>
  )
}
