import Head from 'next/head'
import Header from '../components/header/index'

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Enrolment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header height="h-96"/>
      <div>
        Enrolment
      </div>
    </div>
  )
}
